### ISSUE TITLE
Problem with labels in sumtable

### ISSUE THREAD

**Issue by ccmullally** [NickCH-K/vtable#17]
Based on the documentation, I'm puzzled as to why the first approach works while the second does not. I'm a newbie with respect to R so maybe it's something obvious
```
library('vtable')
library('expss')
data(mtcars)
#Works
label <- data.frame(
  mpg = "Miles per gallon"
)
sumtable(mtcars, group = 'cyl', group.test = TRUE, labels = label)
#does not work
mtcars = apply_labels(mtcars,
                      mpg = "Miles per gallon"
)
sumtable(mtcars, group = 'cyl', group.test = TRUE, labels = TRUE)
```

**Comment by NickCH-K** [comment]
I'm not familiar with the **expss** package but the `apply_labels` function appears to apply a `'labelled'` class to the variable that is typically reserved for labeled *values* rather than labeled *variables*. `sumtable()` ignores `'labelled'` classes with lots of unique values, since they are typically weird **haven** imports that work neither with factor-style or numeric-style summary statistics.

It looks like the `vtable()` function does work with **expss**, but not `sumtable()` for the aforementioned reason. If you'd like to use an alternate package to set labels before passing them to `sumtable(labels = TRUE)`, I'd recommend doing so with a **haven** import or with `set_label()` from **sjlabelled**.

```r
library(sjlabelled)
data(mtcars)
mtcars$mpg <- set_label(mtcars$mpg, 'Miles per Gallon')
sumtable(mtcars, labels = TRUE)
```

I can see maybe trying to make things compatible with the `labelled` class in the future, but **haven** imports wreak such havoc with it I'm not sure how I'd distinguish the good cases from the bad.

**Comment by ccmullally** [comment]
Thank you! This worked great. Also, I tried my way but with Hmisc and it also didn't work, just FYI. 
By the way I'm really enjoying LOST. As a longtime Stata user it's very helpful. Take care.
